name="Sharfudeen"
age=20
height=170.1
weight=60
city="Tirunelveil"
is_student=False
marks=600
pi=3.14
school_name="Andrews Matric Hr Sec School"
print(type(name))
print(type(age))
print(type(pi))
print(type(is_student))
my_number=10
print(type(my_number))
print(my_number)
my_text="hello"
print(type(my_text))
print(my_text)
print(name)
print(age)
print(height)
print(weight)
print(city)
print(is_student)
print(marks)
print(pi)
print(school_name)
